compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.0.2.cjs
