name: 'Lint'
description: 'Ensure the project lint rules are respected'

inputs:
  node-version:
    description: 'Node.js version'
    default: '16'

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-environment
      with:
        node-version: ${{ inputs.node-version }}

    - name: Lint
      run: yarn lint
      shell: bash
